### ISSUE TITLE
[Feature]: FullHeight container's element could be other than just div

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toss/slash#198]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: @toss/emotion-utils

### **Overview**

```tsx
// FullHeight.tsx

export function FullHeight({ children, ...props }: { children: ReactNode } & HTMLAttributes<HTMLDivElement>) {

  return (
    <div> // why only div tag?
      {children}
    </div>
  );
}


```

If you look at the current implementation of FullHeight, it is fixed and wrapped with a `div` container.

However, in actual development, it is often necessary to semantically use `section` or `main` and other elements instead of div containers. In that case, it is inconvenient to use FullHeight. 

I think it would be good to have better scalability!

### **Describe the solution you'd like**

like [`OpenGraph`](https://slash.page/libraries/react/react/src/components/opengraph/opengraph.tsx.tossdocs/)

```tsx
interface Props {
  container?: ComponentType<any>; // accept other tag
}
```

**Comment by manudeli** [comment]
How about `as` prop for that feature(aka. polymorphic component)?

### Proper prop name to provide polymorphic feature
I think Opengraph's container is proper for its meaning because default container is Fragment,
so if anyone use container prop, container will contain children(for opengraph tags).

but I think FullHeight is different case. Default element need to be div like current implementation.
So if you want to add polymorphic feature, I want to suggest that prop name as `as` like Box's as prop of @chakra-ui/react

### More feature expected
If possible, I really expect situation using `@toss/emotion-utils` using `@toss/framer-motion`'s motion.div as 'as prop'.
like Box of `@chakra-ui/react` using motion.div as `as` prop

#### Example: I imaged smooth shrinking animation of FullHeight for emphasize overlay and so easy implementation.

```tsx
const Page = () => {
  const [isShrinkForOverlay, setIsShrinkForOverlay] = useState(false)
  const overlay = useOverlay() // use @toss/use-overlay

  const openFooConfirmDialog = () =>  new Promise<boolean>(resolve => {
	    overlay.open(({ isOpen, close }) => (
	      <FooConfirmDialog
	        open={isOpen}
	        onClose={() => {
	          resolve(false);
	          close();
	          setIsShrinkForOverlay()
	        }}
	      />
	    ));
	  })

  return (
    <FullHeight as={motion.div} initial={{.scale: 1 }} animate={{.scale: isShrinkForOverlay ? 0.9 : 1 }}>
      ...
      <button onClick={openFooConfirmDialog}>Open overlay</button>
    </FullHeight>
  )
}
```

like below picture, overlay with smooth shrinking animation FullHeight Background 😭

![chrome-capture-2023-0-25](https://user-images.githubusercontent.com/61593290/214566143-a7629c07-24a1-438a-bb84-c87a22f3a3d5.gif)

**Comment by ChanhyukPark-Tech** [comment]
@manudeli  Thank you for cool comment!

I agree with you all! It was easy to understand because you explained **why** it was different from OpenGraph.

In fact, I think it would be good to receive the tag of framer-motion in many cases like the example you showed me, so I think it would be good to receive it.

I think it would be good to implement to receive various tags using `as`.
It can be an scalable component.

**Comment by manudeli** [comment]
@ChanhyukPark-Tech @raon0211 

```
in your example
interface Props {
  container?: ComponentType<any>; // accept other tag
}
```

I agree FullHeight, OpenGraph need to accept as, container too.  but I want to comment it for advice.

```tsx
export const Comp2 = (props: { example: string }) => <div />;

export const Comp = () => <FullHeight as={Comp2} example='hi' />; // cannot accept example prop
```

in your example, your component's as prop can accept every components.
but FullHeight can not accept Comp2's props, because of TypeScript's restriction 

However, recently I added this PR https://github.com/toss/slash/pull/201 to use as prop type strictly depending on the accepted component, so ScreenReaderOnly can accept all props of component being accepted as 'as prop'. 

Check below picture to show you how strictly but dynamically, useful auto complete and error by TypeScript.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/61593290/215817046-aaa8cf33-5e0a-4f9b-b7ad-a762c627b6f3.png">

So, Could I make new Pull Request to fix it all(OpenGraph, FullHeight) like this PR https://github.com/toss/slash/pull/201 ?

**Comment by raon0211** [comment]
Yes, polymorphic components may help here, but I'm afraid it might not be an optimal solution.

The reason is that there are some TypeScript performance issues when using polymorphic components. For example, [check this discussion](https://github.com/stitchesjs/stitches/discussions/609). I remember there were some more in emotion and styled-components, but since there are so many issues I couldn't find it.

I believe the better solution might be that `@toss/emotion-utils` just expose the styles as 

```tsx
import { fullHeight } from '@toss/emotion-utils';

<article css={fullHeight} />;
```

This would not differ that much from `<FullHeight as="article" />` and is fully type-safe. And there are no reasons to use polymorphic functions. As a result, code becomes more concise and easier to maintain. What are your thoughts on this?

**Comment by manudeli** [comment]
Oh, I didn't think about TypeScript performance, or emotion, styled-components.

Thanks for providing great insights always.

then how about restricting `as` prop to accept only `keyof InstrinsicElements` string union type like div, span, a or etc.?, Not component we make.

**Comment by ChanhyukPark-Tech** [comment]
@raon0211 thank you for detail comment!

I understood right away after seeing the example you gave me.

After all, it is more comfortable and safer to handle `css` than to handle `as`.
We can use [this function](https://slash.page/libraries/react/emotion-utils/src/utils/height.ts.tossdocs/#height100).
It's so nice to use the components of framer-motion as below! more flexible!

```tsx
<motion.ul css={${height100}}>
...
</motion.ul>
```

**Comment by ChanhyukPark-Tech** [comment]
@manudeli thank you for your great comment!

We can have stability if we can only receive the basic elements `keyof InstrinsicElements `, but we can't take unity in the overall project. I think there will be cases where each component uses it differently!

```tsx
// SomethingOne
<FullHeight as="ul">
...
</FullHeight>
```

```tsx
// SomethingTwo can not use motion.ul in as props 
<motion.ul css={css`
height:100%
`}>
...
</motion.ul>
```

thank you!!😃

**Comment by manudeli** [comment]
> @manudeli thank you for your great comment!
> 
> We can have stability if we can only receive the basic elements `keyof InstrinsicElements `, but we can't take unity in the overall project. I think there will be cases where each component uses it differently!
> 
> ```tsx
> // SomethingOne
> <FullHeight as="ul">
> ...
> </FullHeight>
> ```
> 
> ```tsx
> // SomethingTwo can not use motion.ul in as props 
> <motion.ul css={css`
> height:100%
> `}>
> ...
> </motion.ul>
> ```
> 
> thank you!!😃

Then how about deprecating or re-packaging these components like FullHeight, Flex, Stack, SafeArea etc.?
## Problem - Package's Consistency: Because @toss/emotion-utils's Flex, Stack, SafeArea already accept as prop... but not FullHeight! why? 
### Flex
<img width="540" alt="image" src="https://user-images.githubusercontent.com/61593290/216394465-86bc92cc-0293-495d-9865-70f26b2746d8.png">

### Stack
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/61593290/216395206-c7c7a283-824b-4797-b650-ebe351f769d6.png">

### SafeArea
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/61593290/216394777-e8413097-b339-4d99-9c32-c2f9c97eecf6.png">

How about making @toss/emotion-layout or @toss/emotion-components to contain them deprecated in @toss/emotion-utils with as prop?

I think @emotion-utils need to be more smaller for consistency of functions to make css

I want to suggest name like @toss/emotion-css, @toss/emotion-layout-components to devide role or to make consistency of public api.

1. @toss/emotion-css(?): containing functions like horizontalGutter, verticalGutter, fullheight, flex, spacing etc.
2. @toss/emotion-layout(?) or @toss/emotion-components(?): containing Components like FullHeight, Flex, Spacing, SafeArea containing as prop or not or restricting `as` prop to accept only keyof InstrinsicElements In  like now.

**Comment by raon0211** [comment]
Yes, I understand that consistent APIs are important, so I think in this case we should add an `as` a prop. In the long run, we should provide two options as @manudeli suggested..

**Comment by manudeli** [comment]
@raon0211 
I want to check whether the FullHeight component is allowed to receive only up to the keyof JSX.InstrincElement like Flex, Stack of other @toss/emotion-utils as `as` prop, or whether it is allowed to receive all components(React.ElementType) more broadly like ScreenReaderOnly of @toss/a11y.

> I remember there were some more in emotion and styled-components, but since there are so many issues I couldn't find it. 

I thought other solution restricting `as` prop as `keyof JSX.InstrincElement | keyof motion` of @toss/framer-motion to solve problem in your comment, but allowing `as` prop to accept accepting broadly than before(only keyof JSX.InstrincElement)

Anyway could you guide it for me?

**Comment by raon0211** [comment]
Oh.. if it is for a consistent API, why not start with just `keyof JSX.InstrincElement`, and use `css={fullHeight}` for `Stack` and `Flex`s?

**Comment by manudeli** [comment]
> Oh.. if it is for a consistent API, why not start with just `keyof JSX.InstrincElement`, and use `css={fullHeight}` for `Stack` and `Flex`s?

I made [this Pull Request](https://github.com/toss/slash/pull/221) to solve this Problem. check it out please.

**Comment by ChanhyukPark-Tech** [comment]
I think it's solved to some extent, so I'll close the issue. Thank you so much, both of you @raon0211 @manudeli
