### ISSUE TITLE
[Feature]: Is it useful to take out the `useKey` hook separately?

### ISSUE THREAD

**Issue by minsoo-web** [toss/slash#282]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: `@toss/react`

### **Overview**

Please see follow hooks

[useResetError](https://github.com/toss/slash/blob/main/packages/react/async-boundary/src/hooks/useResetError.ts)
[useKey](https://github.com/toss/slash/blob/main/packages/react/error-boundary/src/hooks/useKey.ts)

I think these hooks are exactly same hook and there purpose for their own Component hook.
`useKey` is useful for user who use key (typed for number) and reseting that key (by increasing), But I doubt that this hook will be used often.

So, Is it useful to take out the `useKey` hook separately?

### **Describe the solution you'd like**

In my opinion, rather than managing the same hook as a local file in multiple packages, it is more useful in terms of management to bring dependencies and use them.

But I doubt that this hook will be used often... 🤔

**Comment by ChanhyukPark-Tech** [comment]
**I don't think there's an answer and I don't think this is an issue**.

 I think the preferred method will be different depending on the developer. It would be better for developers who use vertically long monitors to manage in one file, and for developers who use horizontally long monitors to manage in multiple files.

- I think it's also advantageous to separate the files before they get bigger in the future. 
- It is also neat when conducting a unit test.
 
 Above all, I don't think there will be no big benefit in terms of performance and developer experience when managing it with one file.

**Comment by minsoo-web** [comment]
Can you make sure I understand correctly?

> - I think it's also advantageous to separate the files before they get bigger in the future.
> - It is also neat when conducting a unit test.
> 
> Above all, I don't think there will be no big benefit in terms of performance and developer experience when managing it with one file.

Considering the advantages of separating into one file before it gets bigger and the advantages of unit testing, you seem to be telling me that it's right to separate into one file and modularize it. 

> Above all, I don't think there will be no big benefit in terms of performance and developer experience when managing it with one file.

But I'm a little confused because I think you told me there won't be any benefit at the end.

**Comment by ChanhyukPark-Tech** [comment]
Sorry about my poor english 😂

**I misunderstood the content of the issue and gave you the [wrong answer](https://github.com/toss/slash/issues/282#issuecomment-1619283053)**

I think it's right to have the name of `useResetError`(or something) rather than `useKey`. Because the purpose of the hook itself is to **reset the error**.

I think it depends on a particular situation (domain) because it resets the error while forcing it to rerender (not react way). So I don't think it should be defined in a package that defines a common module such as `@toss/react`.

To make these two hooks common, @toss/async-boundary uses @toss/error-boundary, so it seems appropriate that the hook is defined in @toss/error-boundary and import hook in @toss/async-boundary

**I think it's unnecessary that the hook of the same role is divided into two parts and managed.**

**Comment by minsoo-web** [comment]
Thank you ! 🙇‍♂️

I totally understand what you said.
